name: 'Build verification'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: 20.x
  DOCS_FOLDER: /
  DOCS_VERSION_PATH: /
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pages:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and rebuild SAP manual
        run: |
          npm install &&
          npm run docs:build
